- hosts: all
  vars_prompt:
  -  name: dir_name
     private: no
     prompt: "Enter the directory name on which you want to mount your dvd"
  -  name: content
     private: no
     prompt: "Enter the content of your webpage"               
  tasks:
  - file:
     state: directory
     path: "{{ dir_name }}"
  - mount:
     src: "/dev/cdrom"
     path: "/dvd"
     state: mounted
     fstype: "iso9660"
  - yum_repository:
     baseurl: "/dvd/AppStream"
     name: "mydvd1"
     description: "my yum dvd 1"
     gpgcheck: no
  - yum_repository:
     baseurl: "/dvd/BaseOS"
     name: "mydvd2"
     description: "my yum dvd 2"
     gpgcheck: no
  - package:
     name: "httpd"
     state: present
  - file:
     state: directory
     path: /var/www/lw
  - copy:
     src: my.conf
     dest: /etc/httpd/conf.d/lw.conf 
  - copy:
     content: "{{ content }}"
     dest: "/var/www/lw/index.html"
  - service:
     name: "httpd"
     state: restarted
     enabled: yes
  - firewalld:
     state: enabled 
     port: "8080/tcp"  
     permanent: yes
     immediate: yes  
